import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-termos-uso',
  standalone: true,
  imports: [RouterLink, CommonModule],
  templateUrl: './termos-uso.component.html',
  styleUrl: './termos-uso.component.scss',
})
export class TermosUsoComponent {
  fontesDasImagens = [
    { site: 'Minube', url: 'https://www.minube.com.br/sitio-preferido/rio-de-janeiro-a151' },
    { site: 'Jovem Pan', url: 'https://jovempan.com.br/edicase/aniversario-de-sao-paulo-10-curiosidades-sobre-a-cidade.html' },
    { site: 'Monitor do Mercado', url: 'https://monitordomercado.com.br/noticias/181772-por-que-recife-deveria-estar-no-topo-da-sua-lista-de-viagens/' },
    { site: 'Oliveira Imóveis AL', url: 'https://oliveiraimoveisal.com.br/postagem/maceio-alagoas' },
    { site: 'Gontijo (Facebook)', url: 'https://www.facebook.com/empresagontijooficial/' },
    { site: 'Brasil Infos (Gontijo)', url: 'https://belo-horizonte-mg.brasil-infos.com/empresa-gontijo-de-transportes-5/' },
    { site: 'Águia Branca', url: 'https://www.aguiabranca.com.br/marca' },
    { site: 'ClickBus (Ultra)', url: 'https://www.clickbus.com.br/viacao/ultra' },
    { site: 'Wikipedia (Cometa)', url: 'https://pt.wikipedia.org/wiki/Ficheiro:Logotipo_Cometa.png' },
    { site: 'Mala de Aventuras', url: 'https://www.maladeaventuras.com/melhores-praias-da-bahia/' },
    { site: 'Shutterstock', url: 'https://www.shutterstock.com/pt/search/beach-water-sky' },
    { site: 'Samaria', url: 'https://samaria.com.br/' },
    { site: '99Jobs (Jadlog)', url: 'https://99jobs.com/jadlog' },
    { site: 'Catarinense', url: 'https://www.catarinense.com.br/empresa' },
    { site: 'Viagem e Turismo', url: 'https://viagemeturismo.abril.com.br/cidades/ilha-comprida/' },
    { site: 'Elo7', url: 'https://www.elo7.com.br/frete-sedex-sp-capital/dp/E49C4A' },
    { site: 'Code Market', url: 'https://www.codemarket.com.br/produto/integracao-melhor-envio-oficial-correios-e-transportadoras' },
    { site: 'Pássaro Marron', url: 'https://www.passaromarron.com.br/' },
    { site: 'LogoDownload (Pássaro Marron)', url: 'https://logodownload.org/passaro-marron-logo/' },
    { site: 'Villa del Sol', url: 'https://villadelsol.com.br/blog/ferias-de-julho-em-paraty-estrela-tours/' },
    { site: 'IHG (InterContinental)', url: 'https://www.ihg.com/intercontinental/hotels/br/pt/sao-paulo/saoha/hoteldetail' },
    { site: 'Booking (Palácio Tangará)', url: 'https://www.booking.com/hotel/br/palacio-tangara.pt-br.html' },
    { site: 'Hoteis.com', url: 'https://www.hoteis.com' },
    { site: 'Marazul Receptivo', url: 'https://marazulreceptivo.com.br/blog/hoteis-all-inclusive-natal/' },
    { site: 'Canaltech (Loggi)', url: 'https://canaltech.com.br/mercado/o-que-e-e-como-funciona-a-loggi/' },
    { site: 'Magnific', url: 'https://www.magnific.com/br/fotos-gratis/entregador-feliz-carregando-pacotes-ao-fazer-entrega-em-domicilio-para-seu-cliente_25622123.htm' },

    // Novos links adicionados
    { site: 'Recomendo na Cidade', url: 'https://recomendonacidade.com.br/o-que-fazer-em-cananeia/' },
    { site: 'VSRC', url: 'https://vsrc.com.br/angra-dos-reis/' },
    { site: 'Booking Angra Inn', url: 'https://www.booking.com/hotel/br/angra-inn-angra-dos-reis.en-gb.html' },
    { site: 'Wikimedia Commons', url: 'https://commons.wikimedia.org/wiki/File:Beleza_da_Lagoa_Azul.jpg' },
    { site: 'Estado de Minas', url: 'https://www.em.com.br/empresas/2024/06/6884903-belo-horizonte-veja-um-guia-completo-do-que-fazer-na-capital-mineira.html' },
    { site: 'Facebook Cerrado Mineiro', url: 'https://www.facebook.com/cerradomineiro/posts/310039098454359/' },
    { site: 'Portal Aqui Vale', url: 'https://portalaquivale.com.br/campos-do-jordao-taubate-sao-luiz-e-braganca-paulista-batem-recorde-de-frio/' },
    { site: 'Hotel Marazul Cananeia', url: 'https://hotel-marazul-cananeia.allsaopaulohotels.com/br/' },
    { site: 'Tripadvisor Hotel Amoreiras', url: 'https://www.tripadvisor.com.br/Hotel_Review-g2348883-d2629396-Reviews-Hotel_Amoreiras-Extrema_State_of_Minas_Gerais.html' },
    { site: 'Hotel Villa Lobos', url: 'https://www.hoteis.com/ho647637792/hotel-villa-lobos-extrema-brasil/' },
    { site: 'Blanche Turismo', url: 'https://blancheturismo.com/site/' },
    { site: 'Facebook Expresso União', url: 'https://www.facebook.com/empresaexpressouniao/' },
    { site: 'MyHotel', url: 'https://www.myhotel.cl/en/' },
    { site: 'Nacional Inn', url: 'https://www.nacionalinn.com.br/hotel/dan-inn-premium/promocoes/todas' },
    { site: 'Mercure Porto Bali', url: 'https://www.booking.com/hotel/br/porto-bali-resort-mercure.pt.html' },
    { site: 'Vou na Janela', url: 'https://www.vounajanela.com/brasil/o-que-fazer-em-paraty/' },
    { site: 'Parque Hotel', url: 'https://www.parquehotel.com.br' },
    { site: 'Hotel Serras de Extrema', url: 'https://hotelserrasdeextrema.com.br/conheca-extrema/' },
    { site: 'Esse Mundo é Nosso', url: 'https://www.essemundoenosso.com.br/8-praias-de-paraty/' },
    { site: 'GoTripzi', url: 'https://gotripzi.com/destinations/rio-de-janeiro-br' },
    { site: 'Passageiro de Primeira', url: 'https://passageirodeprimeira.com/roda-rico-lanca-promocao-de-fim-de-ano-com-preco-promocional-para-duas-pessoas-por-r-9999/' },
    { site: 'Autoviação Cambuí', url: 'https://autoviacaocambui.com.br/guia-para-viagens-economicas-por-minas-gerais/' },
    { site: 'Samba Hotéis', url: 'https://sambahoteis.com' },
    { site: 'Wikipedia Ponte Estaiada', url: 'https://en.wikipedia.org/wiki/Oct%C3%A1vio_Frias_de_Oliveira_Bridge' },
    { site: 'Terraço Itália', url: 'https://www.terracoitalia.com.br/' },
    { site: 'Expresso União', url: 'https://www.expressouniao.com.br/pessoas.html' },
    { site: 'Martins Fontes Paulista', url: 'https://www.martinsfontespaulista.com.br/vale-do-ribeira-951500/p' },
    { site: 'booking hoteis', url: 'https://www.booking.com/hotel/br/pousada-aconchego-paraty.pt-br.html?label=pousada-doce-paraty-yR4H4X6Q8uRynr6PuTGfJAS539485593328%3Apl%3Ata%3Ap1%3Ap2%3Aac%3Aap%3Aneg%3Afi%3Atikwd-1626429267%3Alp9198997%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9YbC4OlOULAnvcrFmvh1xnqM&sid=1d1b3ec790e9877edbe6539dc71aedf1&gclid=CjwKCAjwidXQBhAZEiwA4egw6K62YJh47I0MAYaUSikhBiy0eHjQJnACIezLxmRbWEG05OSN5snjZxoCvukQAvD_BwE&aid=1726433&ucfs=1&arphpl=1&dest_id=-659504&dest_type=city&group_adults=2&req_adults=2&no_rooms=1&group_children=0&req_children=0&hpos=3&hapos=3&sr_order=popularity&srpvid=57897ccd1554017b&srepoch=1779817573&from=searchresults&activeTab=photosGallery' },
    { site: 'feciturmg', url: 'https://www.instagram.com/feciturmg/p/DY18-0uHPpY/' },
    { site: 'minas gerais', url: 'https://www.ouvidoriageral.mg.gov.br/canais-atendimento' },
    { site: 'viação santa maria ', url: 'https://www.facebook.com/photo/?fbid=686919070085465&set=a.333224082121634' },
    { site: 'SANTA MARIA viagens', url: 'https://samaria.com.br/viagem-onibus-sao-paulo-curitiba/' },
    { site: 'FELICIDADE', url: 'https://avidaplena.com.br/mais-saude/como-ser-feliz/' },
    { site: 'mulher correndo', url: 'https://www.istockphoto.com/br/fotos/mulher-correndo-com-malas' },
  ];
}
